fix: minor issue with github actions

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -98,7 +98,7 @@ jobs:
         run:  |
           make delete-all-helm-mp-items ENVIRONMENT=$ENVIRONMENT_NAME
           make publish-all-blueprints ENVIRONMENT=$ENVIRONMENT_NAME
-      - name: Cleanup & Reset Cluster
-        if: success() || failure()
-        run: make bootstrap-reset-all ENVIRONMENT=$ENVIRONMENT_NAME
+      # - name: Cleanup & Reset Cluster
+      #   if: success() || failure()
+      #   run: make bootstrap-reset-all ENVIRONMENT=$ENVIRONMENT_NAME
 
